version: '3'

services:

  postgres:
    image: postgres:9.4
    container_name: postgres
    ports:
      - "5432:5432"
    env_file: 
      - ./producer/db/db.env
    volumes:
      - ./producer/db/sql:/docker-entrypoint-initdb.d/ # Add SQL to run
      - db-data:/var/lib/postgresql/data/ # persist even on shutdown

  producer:
    build: ./producer
    container_name: producer
    network_mode: "host"
    depends_on:
      - postgres
    environment:
      KAFKA_BROKER_URL: 'localhost:9092'
      SCHEMA_REGISTRY_URL:  'http://localhost:8081'
      TRANSACTIONS_TOPIC: 'queueing.transactions'
      TRANSACTIONS_PER_SECOND: 5

  consumer:
    build: ./consumer
    env_file: aws.env
    container_name: consumer
    network_mode: "host"
    depends_on:
      - postgres
      - producer
    environment:
      KAFKA_BROKER_URL: 'localhost:9092'
      SCHEMA_REGISTRY_URL: 'http://localhost:8081'
      TRANSACTIONS_TOPIC: 'queueing.transactions'
      LEGIT_TOPIC: 'streaming.transactions.legit'
      FRAUD_TOPIC: 'streaming.transactions.fraud'

volumes:
  db-data:
