version: '3'

services:

  postgres:
    image: postgres:9.4
    env_file: 
      - ./generator/db/db.env
    volumes:
      - ./generator/db/sql:/docker-entrypoint-initdb.d/ # Add SQL to run
      - db-data:/var/lib/postgresql/data/ # persist even on shutdown

  generator:
    build: ./generator
    environment:
      KAFKA_BROKER_URL: broker:9092
      TRANSACTIONS_TOPIC: queueing.transactions
      TRANSACTIONS_PER_SECOND: 1000

  detector:
    build: ./detector
    environment:
      KAFKA_BROKER_URL: broker:9092
      TRANSACTIONS_TOPIC: queueing.transactions
      LEGIT_TOPIC: streaming.transactions.legit
      FRAUD_TOPIC: streaming.transactions.fraud

networks:
  default:
    external:
      name: kafka-network
